### ISSUE TITLE
Hi，大佬，想问一下，当前MarkLLM支持中文么？

### ISSUE THREAD

**Issue by ruyiluo** [THU-BPM/MarkLLM#1]

**Comment by panly2003** [comment]
您好~ MarkLLM这个框架本身是和语言无关的，是否支持中文取决于用户使用的生成文本的LLM是否支持中文，以及选取的水印算法是否支持中文。目前来看，已经整合在MarkLLM框架中的9种水印算法都是支持中文的。

**Comment by ruyiluo** [comment]
好的，感谢
