### ISSUE TITLE
KGW parameter setting

### ISSUE THREAD

**Issue by Allencheng97** [THU-BPM/MarkLLM#20]
Dear authors,

Thank you for your great work! I have a question regarding the implementation of KGW algorithms in this repo. 
In the original paper, there's a paramter k in KGW, the k is the number of preceding tokens to hash.
I am wondering which variable represent this k in the config file?

Thank you very much for your attention. I am looking forward to hearing from you soon.

Best,

**Comment by panly2003** [comment]
The parameter ‘prefix_length’ in the configuration file corresponds to the number of preceding tokens to be hashed. 😊

**Comment by Allencheng97** [comment]
> The parameter ‘prefix_length’ in the configuration file corresponds to the number of preceding tokens to be hashed. 😊

Got it! Thank you very much for your reply.
