### ISSUE TITLE
top_k

### ISSUE THREAD

**Issue by mignonjia** [THU-BPM/MarkLLM#3]
Hello authors, 

Congratulation on this great repo! I have a question regarding to the generation configuration. It seems you are using the default value of top_k=50 in Hugging Face for KGW-based methods, but for EXP and EXP-edit, you are using all tokens to generate. 

Using top_k = 50 will significantly reduce PPL. So do you think it's fair to also test EXP and EXP-edit using top_k = 50? A one-line code to add this filter in the EXP and EXP-edit should be enough.

**Comment by panly2003** [comment]
Thank you for the insightful feedback and suggestion! You raise an excellent point. Maintaining consistency in the generation configuration is indeed important for fair comparisons across methods.

Using top_k=50 can significantly reduce the perplexity (PPL). For a more equitable evaluation, we agree that it would be valuable to also test EXP and EXP-edit with top_k=50.

Furthermore, we'll consider adding a filter parameter to the EXP and EXP-edit configs. Thanks again for the thoughtful recommendation!
