### ISSUE TITLE
[feature request] TextEditor for truncating natural text to max watermarked text length

### ISSUE THREAD

**Issue by jonasschaefer** [THU-BPM/MarkLLM#31]
hi, I believe you should implement a `TextEditor` that truncates an unwatermarked text to a specified length (cuts off extra tokens). this would be useful to achieve comparable detection scores for watermarked and unwatermarked texts because they should be roughly the same length (same number of tokens). as of now, we can generate watermarked text with `max_new_tokens=200`, but the natural completion might still have many more tokens, which will give us a clearer (usually weaker) signal. it would be better to compare texts with the same number of tokens.

**Comment by panly2003** [comment]
Thank you for your suggestion! We appreciate your input on the TextEditor functionality. However, we believe that handling natural text should be part of the dataset processing step. Users can preprocess their data and provide the processed data path when initializing the dataset. Truncating natural text to a specific length is a relatively straightforward operation, and we recommend users to handle this on their own. Thanks!

**Comment by jonasschaefer** [comment]
okay, that works too. thank you!
