### ISSUE TITLE
What are the optimal parameters for the SynthID-Text method?

### ISSUE THREAD

**Issue by liudan193** [THU-BPM/MarkLLM#40]
What are the optimal parameters for the SynthID-Text method?

In my tests, I find that when using the provided default parameters, I achieve very good perplexity (PPL) but low robustness.

**Comment by exlaw** [comment]
To improve robustness, you typically need to reduce the "ngram_len" value. We referenced the hyperparameters from the original GitHub repository and chose 5. Generally, the smaller the ngram_len, the better the robustness will be.

**Comment by liudan193** [comment]
Thanks for your reply, I will take a try.
